### ISSUE TITLE
Docx report issues

### ISSUE THREAD

**Issue by EmiliaChovancova** [CervantesSec/cervantes#51]
### Tables  
- if you choose the table style attribute border = “0” or none and set the <tr> style attribute of “border-bottom” to whatever color it doesn’t work in the downloaded docx report. It’s working with HTML version of the downloaded report and it is also working with various html editors but not in the docx format. 

HTML downloaded report (working):
![html_dowloaded_report](https://github.com/user-attachments/assets/6f2678a9-7da8-426f-84a5-bd85848b9185)

Docx format report - not working :( 
<img width="389" alt="doxc_report_downloaded" src="https://github.com/user-attachments/assets/0b1e128b-289c-4c95-9270-624f4bc67ac6">

### Steps to reproduce 
1. Create a simple table - for example like this:
```html
<table style="border-collapse: collapse; width: 60%; height: 44.7812px; margin-left: auto; margin-right: auto;"><colgroup><col style="width: 33.7296%;"><col style="width: 32.9883%;"><col style="width: 33.2662%;"></colgroup>
<thead>
<tr style="border-bottom: 1px solid rgba(169, 169, 169, 1); border-top: 1px solid rgba(169, 169, 169, 1); height: 22.3906px;">
<th style="color: rgba(238, 0, 0, 1); height: 22.3906px; text-align: left;"><span style="font-size: 10pt;">A</span></th>
<th style="color: rgba(238, 0, 0, 1); height: 22.3906px; text-align: left;"><span style="font-size: 10pt;">B</span></th>
<th style="color: rgba(238, 0, 0, 1); height: 22.3906px; text-align: left;"><span style="font-size: 10pt;">C</span></th>
</tr>
</thead>
<tbody>
<tr style="height: 22.3906px;">
<td style="height: 22.3906px;"><span style="font-size: 10pt;">D</span></td>
<td style="height: 22.3906px;"><span style="font-size: 10pt;">E</span></td>
<td style="height: 22.3906px;"><span style="font-size: 10pt;">F</span></td>
</tr>
</tbody>
</table>
``` 
2. Generate and download a docx report. 

---

### Images 
-  Images in components are not positioned as defined in docx reports - if you choose to set a picture to the right side of the page with attributes like “img style="float: right; margin: 0 0 15px 15px;"” the image is always in a completely different place. 

Preview in Cervantes, downloaded HTML report or external HTML editors are working correctly:
![preview_cervantes](https://github.com/user-attachments/assets/c38eed65-de1b-4924-9c4c-f5c0197ed2ce)

But again, the docx report is not working :( image is on the left side of the page even though the parameters were set to the right side:

![DOCXreportDownloaded](https://github.com/user-attachments/assets/c4e34054-979c-4bc8-a11f-4914f58ac506)

### Steps to reproduce 

1.  Insert an image to the component
2. Adjust the html code to for example:
```html
<p style="page-break-inside: avoid; margin-bottom: 0.14in; page-break-after: avoid; position: relative;"><img style="float: right; margin: 0 0 15px 15px;" src="blob:https://SourceOfTheImage" width="338" height="310"></span></p>
```

**Comment by mesquidar** [comment]
Hi @jstangle thanks for reporting this issue I will take it a look and I will let you know :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi  @EmiliaChovancova  I found the issue it's a known bug on a library used to convert the html code to openxml format I did a downgrade of the library until it's fixed in the nexts days :)

I created a dev image if you want to test it before to commit the changes 

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by EmiliaChovancova** [comment]
Hi @mesquidar, It looks like the functionality is still not working. The library that is used to convert the html to xml declares that it supports “margin”, but even after you downgraded the library the image is still not exactly, where it is supposed to be. I would create an issue with the library as it is not a cervantes bug but the html2openxml library, wdyt?

**Comment by EmiliaChovancova** [comment]
Hi @mesquidar, wdyt about my proposal?
Thank you :)

**Comment by mesquidar** [comment]
Hi @EmiliaChovancova sorry I didn't saw your message. Yes sure you can open an issue I updated the library to a new version but seems that image and table width still persists

Thank you :)

**Comment by onizet** [comment]
Hi @EmiliaChovancova, I'm trying to reproduce your issue with the image in the header/footer.
I cannot make it fail, specifying images in header/footer/body or header/footer with text only. Whatever I try, it's not crashing on my hand.
Can you please mp me  (onizet__hotmail.com) your "template" docx and the html you want to convert?
Thank you

**Comment by mesquidar** [comment]
Hi @EmiliaChovancova I built a new dev image with new version of html2openxml 3.1.1 that @onizet released

If you want to test it :)

Best regards

**Comment by jstangle** [comment]
Hi @mesquidar, thank you for the update. I just tested the latest release and it is not crashing. Unfortunately, the images in the header and footer of the HTML are not displaying in the DOCX report.

**Comment by mesquidar** [comment]
Hi @jstangle thanks for the feedback. Can you comment the issue  in https://github.com/onizet/html2openxml/issues/159 so in this case @onizet can manage it 

Thank you :)

**Comment by mesquidar** [comment]
Hi @jstangle @EmiliaChovancova to give some updates I added now the possibility to add your own CSS in the report components so this makes possible to create more customized reports if you want to test it's already available in the dev image (Keep in mind that some css will not be exported correctly to docx due how openxml styling works)

Thank you :)

**Comment by onizet** [comment]
Hi @mesquidar, I would suggest that you use [PreMailer](https://www.nuget.org/packages/PreMailer.Net) to inline the CSS on the html elements. More would be considered during the conversion.

**Comment by mesquidar** [comment]
Hi @onizet yes I am using it to inline the CSS I saw it that you comment it in your documentation

Thank you :)

**Comment by EmiliaChovancova** [comment]
Hi @mesquidar, thank you for the update, we will take a look at it:)

Thank you:)

**Comment by jstangle** [comment]
Hi @mesquidar, I hope you are doing well. During our testing of DOCX template, we identified a few additional issues:

**- Header and Footer Not Reflected on Cover Page in Exported DOCX:**
When exporting a document to DOCX format, the header and footer are missing on the cover page.
**- Table Properties (Borders and Alignment) Not Reflected in Exported DOCX:**
When exporting a document to DOCX format, table settings such as borders and alignment are not preserved.
**- Images Extend Beyond Page Boundaries in Exported DOCX:**
Images, including screenshots, are not properly scaled or positioned in the exported DOCX file, causing them to extend beyond page boundaries.

Please let me know if you require any additional information or steps to reproduce the issue.

**Comment by onizet** [comment]
Hi @jstangle , can you please create a workitem in that repo https://github.com/onizet/html2openxml/issues, while providing your html (and if you are using a specific docx/dotx template).
Thank you

**Comment by jstangle** [comment]
Hi @onizet, I opened two workitems with you:
Table Properties (Borders and Alignment) Not Reflected - https://github.com/onizet/html2openxml/issues/187
Images Extend Beyond Page Boundaries - https://github.com/onizet/html2openxml/issues/188

I still think image scaling is something that needs to be discussed with @mesquidar as well. I'm not sure what the most sensible approach would be to handle this, but it might be helpful to start using predefined CSS scaling for template components and set `class="a4-image"` as the default for inserted images. What do you think?

Header and Footer Not Reflected on Cover Page - I don't think this issue is caused by the html2openxml library itself, but please let me know if I am wrong.

**Comment by mesquidar** [comment]
Hi @jstangle Header and Footer Not Reflected on Cover Page it was intended like that to not appear on the cover. I can try to add a check if you want header and footer on the cover page. And about the rest of issue I saw that you already managed it with @onizet :)

**Comment by jstangle** [comment]
Hi @mesquidar thank you for the clarification. If the intention was for Cover Page to work this way, then that's fine. I found a workaround and will not use the cover page to ensure the header and footer remain on the first page. However, I discovered an issue here, even if I don't insert the cover page into the template, the first page still exports as blank in the DOCX file. Let me know if you need more details.

**Comment by jstangle** [comment]
Hi @mesquidar, please do you have any update on the blank page issue in the DOCX? Let me know if you need any additional information.

**Comment by mesquidar** [comment]
Hi @jstangle I will take it a look in the next weeks I am on medical leave now 🙏

Thanks :)
Best regards

**Comment by jstangle** [comment]
Thank you @mesquidar! Get well soon. 🙏

**Comment by mesquidar** [comment]
Hi @jstangle I created a new dev image that fixes the blank page if you want to try :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by jstangle** [comment]
Hi @mesquidar thank you for the update. I can confirm that the blank page no longer appears in the DOCX file when a cover page is not defined. :)

**Comment by jstangle** [comment]
Hi @mesquidar, it seems that all our DOCX issues have been resolved with the latest release of the html2openxml library.
https://github.com/onizet/html2openxml/releases/tag/3.2.3.

**Comment by mesquidar** [comment]
Hi @jstangle I created a new dev image if you to test it :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by mesquidar** [comment]
I made some test and seems is working right If you confirm me I will close the issue :)

PD: Thanks @onizet ! :)

**Comment by jstangle** [comment]
Hi @mesquidar, thank you for the update and work on this. I think a small adjustment is needed to scale the images properly within the boundaries. I tested setting images with style="width:100%" before exporting them to DOCX, and it works as expected. However, I'm not sure if you can make any adjustments in TinyMCE or Cervantes to add it to images by default. https://github.com/onizet/html2openxml/issues/188.
```
<p><img src="blob:https://localhost/c7c2df49-9c74-4e64-9869-96e1a40b42e6"></p>
<p><img style="width: 100%;" src="blob:https://localhost/c7c2df49-9c74-4e64-9869-96e1a40b42e6"></p>
```

**Comment by mesquidar** [comment]
Hi @jstangle I was taking a look into it and I found a solution, when you generate a docx  images that are inside the "body" Cervantes will check if there's any style: width applied on the image if this don't exist it will apply style="width:100% by default

On header, footer and cover it will remains the same but I will apply style="width:100% on the advanced css and you will have the opportunity to change it

I created a new dev image if you to test it, on this image the changes on header, footer and cover are not applied :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by jstangle** [comment]
Hi @mesquidar, thank you for the solution. I tested the image and it works very well. :) I think we can close the issue now.
